### ISSUE TITLE
Design AboutUs Page

### ISSUE THREAD

**Issue by oathar** [Arpit1037/Travel-Iternary#15]
![image](https://github.com/user-attachments/assets/441ddda6-53c0-4906-880a-b636092910a8)

**Comment by Arpit1037** [comment]
I have designed the About Us page as requested. The page includes a detailed description of our mission, values, and the services we offer. The CSS has been styled to ensure a clean and professional look. Please review the latest changes and let me know if any further adjustments are needed before we close this issue. Thank you!
